Traceback (most recent call last):
  File "/home/dbuchan/Projects/profile_drift/msa_transformer_investigation/esm_seq_generator.py", line 393, in <module>
    read_pfam_alignments(sys.argv[2], drift_families, msa_transformer, msa_transformer_alphabet)
  File "/home/dbuchan/Projects/profile_drift/msa_transformer_investigation/esm_seq_generator.py", line 339, in read_pfam_alignments
    generate_seqs(msa, msa_transformer, msa_transformer_alphabet, align_name, mask_amount[0], mask_amount[1])
  File "/home/dbuchan/Projects/profile_drift/msa_transformer_investigation/esm_seq_generator.py", line 296, in generate_seqs
    msa_transformer_predictions[name] = msa_transformer(msa_transformer_batch_tokens)
  File "/home/dbuchan/virtualenvs/profile_drift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dbuchan/virtualenvs/profile_drift/lib/python3.10/site-packages/esm/model/msa_transformer.py", line 157, in forward
    x += self.embed_positions(tokens.view(batch_size * num_alignments, seqlen)).view(x.size())
  File "/home/dbuchan/virtualenvs/profile_drift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dbuchan/virtualenvs/profile_drift/lib/python3.10/site-packages/esm/modules.py", line 243, in forward
    raise ValueError(
ValueError: Sequence length 2049 above maximum  sequence length of 1024
